### PR TITLE
Project Setup

### PR DESCRIPTION
**Pull request by DammyShittu**
## In this PR,
- `npx create-react-app app-name` was ran to create a new React app.
- Linter files were correctly set up.
- Linter errors were checked and fixed.
- The application runs in the browser without errors.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
- [ ] Please add a proper descriptive Readme in your project. Currently, you have Readme which doesn't meet the standards. Keep the Readme updated at each milestone. 
- [ ] [Optional] Please add proper descriptive commit messages. `Fix Linter Errors` is not a descriptive commit. It can be improved with the respective error name etc. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by DammyShittu** [comment]
Hi @arslanbisharat ,
Thank you for the review. I will work on the required changes now.

**Comment by DammyShittu** [comment]
Hey @arslanbisharat 
I have rewritten the README file to make it more descriptive.
I will proceed to request another review now. 
Thank you 👍

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by DammyShittu** [comment]
Thank you, Arslan 🚀

**Pull request merged**
